### ISSUE TITLE
mritd/shadowsocks有问题

### ISSUE THREAD

**Issue by 2767321434** [mritd/docker#6]
在arukas.io配置后要不是启动不了，就是启动了后
There is no running container
或者一直变ip和端口，docker没有重启，自己在变很是奇怪

**Comment by mritd** [comment]
这不是镜像问题，arukas.io 运行 docker 肯定不是简单的宿主机运行；它内部肯定采用了类似 kubernnetes 等编排工具；这些编排工具会自动负载宿主机的压力；也就是说可能出现 容器漂移，比如你创建了 10 个容器，分布在5 个机器上；则不同时刻、不同情况，如 某一台主机宕机或负载过高，这个 容器会自动迁移到其他宿主机；所以你会发现底下的 地址一直在变；但是 他们上层提供一个不变的 地址；不过经过我测试这个地址只支持 HTTP 协议貌似，所以无解。

**Comment by mritd** [comment]
@2767321434 其实 樱花提供 api 接口让你能够实时查询底层 地址变化的。。。可以写个程序去监控他，然后定时刷新本地 ss 配置。。。不过感觉这么做成本太高，也没必要；简单的办法就是启动多个，然后 负载均衡，隔段时间更新一下

**Comment by 2767321434** [comment]
我也感觉是这个容器的问题，本地测试很多能正常运行的，放到上面总是部署不成功

**Comment by mritd** [comment]
@2767321434 今天早上测试的 
![_221](https://cloud.githubusercontent.com/assets/13043245/24337714/5f84e73e-12d2-11e7-8654-95a77e72fbef.png)

不过我测试时发现一个很大问题，樱花平台现在很不稳定；在我使用同样命令 多次部署有 大约 1/3 概率会成功；剩下 2/3 通过 反复修改端口 save 操作折腾几次也会成功。。。在成功后也会有很大机率 显示 容器运行但是网页不显示暴露端口和链接的得情况。。。到现在 基本时这个状态

![_222](https://cloud.githubusercontent.com/assets/13043245/24337947/2f5b9aa6-12d4-11e7-9cd9-dc3010de84d3.png)

所一说不是镜像问题

**Comment by 2767321434** [comment]
恩，感觉是官方在限制fq代理类的镜像了，各种错误

**Comment by mritd** [comment]
@2767321434 代理走的是 底层的 tcp 或者 udp 协议；而 樱花 最初目的是做 web 服务，也就是HTTP 协议；所以你看以前 底层 地址不断变化，而上层 entrypoint 地址是固定的；我估计后面应该就是跑着 kubernetes；而且我最近了解到 很多黑产行业利用这种开放平台做 DDOS 攻击源；所以估计以后这些平台都会封锁底层协议暴露

**Comment by pengwugithub** [comment]
使用环境变量容器可以运行起来，但是shadowsocks和kcptun不能正常工作。
下面是环境变量
KCP_CONFIG = -t 127.0.0.1:6443 -l :6500 -mode fast2
SS_CONFIG = ss :: -s 0.0.0.0 -p 6443 -m aes-256-cfb -k test123 --fast-open
KCP_FLAG = true
SS_MODULE = ss-server

**Comment by mritd** [comment]
@pengwugithub 变量值加引号

**Comment by xiaoyao1995** [comment]
/root/entrypoint.sh -k 580234 -w 2 -f -p 5000 -c "{\"listen\":\":20000\",\"target\":\"127.0.0.1:5000\",\"key\":\"kcptun\",\"crypt\":\"salsa20\",\"mode\":\"fast\",\"mtu\":1350,\"sndwnd\":1024,\"rcvwnd\":1024,\"datashard\":10,\"parityshard\":3,\"dscp\":46,\"nocomp\":true,\"acknodelay\":false,\"nodelay\":0,\"interval\":20,\"resend\":2,\"nc\":1,\"sockbuf\":4194304,\"keepalive\":10,\"log\":\"/var/log/kcptun.log\"}"怎么失效了。都运行3个月了

**Comment by mritd** [comment]
@xiaoyao1995 最新的请参考  https://hub.docker.com/r/mritd/shadowsocks/

**Comment by xiaoyao1995** [comment]
日志显示请重新启动。我未添加ENV.直接CMD                。需要吧/root删掉是吗。现在的新脚本需要添加变量才能运行吗请问

**Comment by xiaoyao1995** [comment]
![image](https://cloud.githubusercontent.com/assets/24150058/25777854/e94644de-331d-11e7-89b8-634e2f9c5e5b.png)

**Comment by mritd** [comment]
你的 image 栏 如果不加版本，那么默认运行 最新版本；最新版本的使用方式 请参考这里 https://hub.docker.com/r/mritd/shadowsocks/，最新版本参数格式都做了调整；文档中有 样例命令

**Comment by xiaoyao1995** [comment]
image 栏 如果添加版本。谢谢。ps:我是用在路由器上。

**Comment by mritd** [comment]
mritd/shadowsocks:3.0.6 ，如果不写的话相当于 mritd/shadowsocks:latest

**Comment by xiaoyao1995** [comment]
谢谢指点

**Comment by xiaoyao1995** [comment]
Failed to get container stdout/stderr log.    Please retry watch button.已经出现新的问题。是否需要把/root删除

**Comment by staryang8835** [comment]
Kcptun not started......
Starting shadowsocks......
 2019-03-01 20:13:17 INFO: using tcp fast open
 2019-03-01 20:13:17 INFO: initializing ciphers... aes-256-cfb
 2019-03-01 20:13:17 INFO: tcp server listening at 0.0.0.0:6000
 2019-03-01 20:13:17 INFO: running from root user

请问log里报Kcptun not started......是否正常？

**Comment by mritd** [comment]
正常，因为你没有启动 kcptun
